// ============================================
// SECURITY CONFIGURATION
// ============================================
// Generated by setup wizard. Edit as needed.
// Run `npm run setup:security` to reconfigure.

export const security = {
  // ═══════════════════════════════════════════════════════
  // RATE LIMITING
  // ═══════════════════════════════════════════════════════
  rateLimit: {
    enabled: false,
    login: {
      maxAttempts: 5,
      windowMs: 60000,
    },
    api: {
      maxAttempts: 100,
      windowMs: 60000,
    },
  },

  // ═══════════════════════════════════════════════════════
  // ACCOUNT LOCKOUT
  // ═══════════════════════════════════════════════════════
  lockout: {
    enabled: false,
    maxFailedAttempts: 5,
    lockoutDurationMs: 900000,
    showRemainingAttempts: true,
  },

  // ═══════════════════════════════════════════════════════
  // PASSWORD REQUIREMENTS
  // ═══════════════════════════════════════════════════════
  password: {
    minLength: NaN,
    maxLength: 128,
    requireUppercase: false,
    requireLowercase: false,
    requireNumbers: false,
    requireSymbols: false,
  },

  // ═══════════════════════════════════════════════════════
  // SESSION SECURITY
  // ═══════════════════════════════════════════════════════
  session: {
    invalidateOnPasswordChange: false,
    maxConcurrentSessions: null,
  },

  // ═══════════════════════════════════════════════════════
  // AUDIT LOGGING
  // ═══════════════════════════════════════════════════════
  audit: {
    enabled: false,
    storage: 'database' as 'database' | 'console',
    events: [
      'LOGIN_SUCCESS',
      'LOGIN_FAILED',
      'LOGOUT',
      'REGISTER',
      'PASSWORD_CHANGED',
      'ACCOUNT_LOCKED',
      'ACCOUNT_UNLOCKED',
    ] as const,
    retentionDays: 90,
  },
} as const;

export type SecurityConfig = typeof security;
export type AuditEvent = (typeof security.audit.events)[number];
